#!/bin/sh
# regenerates gazette/_trail.md — the `## trail` section of the 5 freshest posts — for the memory barrel import.
# a trail is ≤3 lines per post (shipped / open / state); the post bodies stay on disk, read on demand.
dir="$HOME/frame/cclio/gazette"
out="$dir/_trail.md"
{
  echo "# gazette trail — the 5 freshest posts, 3 lines each (generated by gazette-trail.sh, never edit; full posts in this dir on demand)"
  for g in $(ls -r "$dir"/[0-9]*.md 2>/dev/null | head -5); do
    echo; echo "## $(basename "$g" .md)"
    awk '/^## trail/{f=1;next} f&&/^## /{f=0} f' "$g" | sed '/^$/d'
  done
} > "$out"
# the cw snapshot rides the same moment: every gazette post is a halt, and the compile is ~1 s.
node "$HOME/frame/script/skill-cclio-mode-snapshot.ts" >/dev/null 2>&1 || true
