#!/bin/sh
# regenerates gazette/_recent.md — the 7 freshest posts, frontmatter stripped — for the memory barrel import.
# hook stdout is size-capped (7 posts blew it, 2026-09-02); memory imports are not.
dir="$HOME/dotfiles/cclio/gazette"
out="$dir/_recent.md"
{
  echo "# gazette — 7 freshest posts (generated by gazette-recent.sh, never edit; older posts on demand)"
  for g in $(ls -t "$dir"/[0-9]*.md 2>/dev/null | head -7); do
    echo; echo "### $(basename "$g")"
    awk 'NR==1&&/^---$/{f=1;next} f&&/^---$/{f=0;next} !f' "$g"
  done
} > "$out"
