#!/bin/sh
# regenerates gazette/_recent.md — the 5 freshest posts, frontmatter stripped — for the memory barrel import.
# hook stdout is size-capped (7 posts blew it, 2026-09-02); memory imports are not.
dir="$HOME/dotfiles/cclio/gazette"
out="$dir/_recent.md"
{
  echo "# gazette — 5 freshest posts (generated by gazette-recent.sh, never edit; older posts on demand)"
  for g in $(ls -t "$dir"/[0-9]*.md 2>/dev/null | head -5); do
    echo; echo "### $(basename "$g")"
    awk 'NR==1&&/^---$/{f=1;next} f&&/^---$/{f=0;next} !f' "$g"
  done
} > "$out"
# the cw snapshot rides the same moment: every gazette post is a halt, and the compile is ~1 s.
node "$HOME/dotfiles/script/skill-cclio-mode-snapshot.ts" >/dev/null 2>&1 || true
# the cw memory mirror rides it too — a gazette post is exactly what its rolling window waits for.
node "$HOME/dotfiles/script/skill-memory-sync-mirror.ts" >/dev/null 2>&1 || true
