// writes the swift half of the carbon keycode table from the one in hotkeys/chord.ts.
//   pnpm monitor-hotkey:keycodes           → regenerate keycodes.swift
//   pnpm monitor-hotkey:keycodes --check   → exit 1 if it is out of date, print nothing else
//
// the two tables were kept in step by hand and drifted anyway: 95 codes on the swift side, 66
// on the typescript one, and the 38 the daemon knew that the readers did not turned pageup and
// pagedown into `key116` and `key121` on the board. they never disagreed about a code — which
// is why a union was safe — they were simply two lists nobody diffed.
//
// the direction is typescript → swift because the daemon is the side that costs something to
// change: it is ad-hoc signed, so a new binary means a new cdhash and dima re-granting Input
// Monitoring by hand. generating means that price is paid when the TABLE changes, never when
// someone edits the file next to it.
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { keyCap } from '../hotkeys/chord.ts';

const target = join(
    import.meta.dirname,
    '../schedule/jobs/x-monitor-hotkey-stats/keycodes.swift',
);

const rows = Object.entries(keyCap)
    .map(([code, cap]) => [Number(code), cap] as const)
    .sort((a, z) => a[0] - z[0])
    .map(([code, cap]) => `    ${code}: ${swiftString(cap)},`)
    .join('\n');

const generated = `// Generated by \`pnpm monitor-hotkey:keycodes\` from hotkeys/chord.ts — do not edit.
// That file is the one table; this is its swift view, committed so the build is reproducible
// and a drift shows up as a diff. \`hotkeys/keycodes.test.ts\` fails the commit when the two
// fall out of step.
//
// US-layout virtual keycodes. The modifier codes (54–63) are never looked up here — a
// modifier produces flagsChanged, never keyDown — and are carried anyway so one table serves
// both sides. The daemon's own \`modifierName\` answers a different question and is hand-kept.
let keyCap: [Int64: String] = [
${rows}
]
`;

if (process.argv.includes('--check')) {
    const current = readFileSync(target, 'utf8');
    if (current === generated) process.exit(0);

    console.error(
        `${target} is out of date — run \`pnpm monitor-hotkey:keycodes\`.`,
    );
    process.exit(1);
}

writeFileSync(target, generated);
console.log(`wrote ${Object.keys(keyCap).length} codes to ${target}`);

/* Helpers */
// Swift string literals take the same two escapes this table can ever need: the backslash key
// is in it, and a double quote would be if a layout ever put one on a cap.
function swiftString(value: string) {
    return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}
